More workspaces tests
uclapi/uclapi pull request #2968
Opened 2020-11-15 22:12 UTC by greenfrogs

## What does this PR do?
Adds tests for all workspaces cache components

## ✅ Pull Request checklist

- [x] Is this code complete?
- [x] Are tests done/modified?

## 🚨 Is this a breaking change for API clients?
No

2020-12-08 02:46 UTC, ILW8 commented on backend/uclapi/workspaces/views.py
> +                "error": ("The image with the ID you requested " "does not exist."),
can drop parentheses and two quotes

2020-12-08 02:47 UTC, ILW8 commented on backend/uclapi/workspaces/views.py
> +                "error": ("You specified a response format that " "was not either raw or base64."),
same as the above comment

2020-12-08 02:47 UTC, ILW8 commented on backend/uclapi/workspaces/views.py
> +                "error": ("The survey filter you provided is invalid. " "Valid survey filters are: ")
can drop parentheses and two quotes

2020-12-08 02:48 UTC, ILW8 commented on backend/uclapi/workspaces/views.py
> +                "error": ("The survey filter you provided is invalid. " "Valid survey filters are: ")
same as above

2020-12-08 02:48 UTC, ILW8 commented on backend/uclapi/workspaces/views.py
> +                "error": ("The survey filter you provided is invalid. " "Valid survey filters are: ")
same as above

2020-12-08 03:01 UTC, ILW8 reviewed
Looks good overall. One note about adding cur_time to `cache_historical_time_usage_data`, otherwise only small formatting issues in `views.py`

2020-12-08 10:23 UTC, greenfrogs commented on backend/uclapi/workspaces/occupeye/cache.py
> +    def cache_historical_time_usage_data(self, survey_id, day_count, cur_date=datetime.now()):
Yes we could and using freezegun makes for better tests. But unless we are using freezegun elsewhere, this solution does not change the function signature. cur_date is completely optional. However saying all of that it prevents the testing of cache_historical_time_usage_data from other functions (for example feed_cache) so we probably want to change it.

2020-12-08 10:24 UTC, greenfrogs commented on backend/uclapi/workspaces/views.py
> +                    "You did not specify how many days of historical data " "should be returned. Valid options are: "
Thank you

2020-12-12 10:13 UTC, ILW8 commented on backend/uclapi/workspaces/occupeye/cache.py
> +    def cache_historical_time_usage_data(self, survey_id, day_count, cur_date=datetime.now()):
It does look like freezegun is [being used elsewhere](https://github.com/uclapi/uclapi/blob/1a9bfd2fd3cbbf213b2ae360d57939af553ca08d/backend/uclapi/common/tests.py#L30)!

2020-12-17 17:45 UTC, greenfrogs commented on backend/uclapi/workspaces/occupeye/cache.py
> +    def cache_historical_time_usage_data(self, survey_id, day_count, cur_date=datetime.now()):
Updated!

2020-12-17 21:55 UTC, ILW8 submitted a review, later dismissed
Looks good

2020-12-17 23:00 UTC, zipy124 requested changes
See attached comment. Apart from that absolutely beautiful, ready to get to master when the small change is implemented (or you decide isn't needed :shrug: )

2020-12-18 21:48 UTC, greenfrogs commented on backend/uclapi/workspaces/management/commands/feed_occupeye_cache.py
> +                import sys
I agree, this should be at the top of the file.

2020-12-18 22:20 UTC, merged

2020-12-18 22:59 UTC, ILW8 commented
Looks even better 👍